workflows:
  ios-release:
    name: Build iOS Release
    max_build_duration: 60
    ios:
      build: |
        flutter clean
        flutter pub get
        flutter build ios --release
    artifacts:
      - build/ios/iphoneos/Runner.app
