name: my_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.0
  cloud_firestore: ^5.6.1
  firebase_auth: ^5.3.2
  provider: ^6.1.2
  google_fonts: ^6.2.1
  syncfusion_flutter_charts: ^28.2.6
  table_calendar: ^3.0.8
  flutter_staggered_grid_view: ^0.6.1
  fl_chart: ^0.70.1
  shimmer: ^2.0.0
  image: ^4.5.2
  cupertino_icons: ^1.0.2
  image_picker: ^1.1.2
  cloudinary_sdk: ^5.0.0+1
  flutter_image_compress: ^2.4.0
  google_maps_flutter: ^2.1.1
  location: ^8.0.0
  permission_handler: ^11.4.0
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  sensors_plus: ^6.1.1
  flutter_polyline_points: ^2.1.0
  geocoding: ^3.0.0
  google_places_flutter: ^2.1.0
  sqflite: ^2.4.2
  uuid: ^4.5.1  
  heif_converter: ^1.0.1
  geolocator: ^13.0.3
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.5
  latlong2: ^0.9.1
  flutter_foreground_task: ^8.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/tranquilgo_logo.png"

flutter_native_splash:
  color: "#ffffff" 
  image: "assets/images/tranquilgo_logo.png" 
  android: true
  ios: true
