// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqpiJr74Al3s1I4BXZ4X11aiBeRYeKXhg',
    appId: '1:17515297820:web:5768b981742b0b2239f3d9',
    messagingSenderId: '17515297820',
    projectId: 'tranquilgo-594b2',
    authDomain: 'tranquilgo-594b2.firebaseapp.com',
    storageBucket: 'tranquilgo-594b2.firebasestorage.app',
    measurementId: 'G-5T9Q6L93Q8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSlfo4Jkf7NMTxlmjjLMuAiL3jvdsznT8',
    appId: '1:17515297820:android:763eb564f72b778539f3d9',
    messagingSenderId: '17515297820',
    projectId: 'tranquilgo-594b2',
    storageBucket: 'tranquilgo-594b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-L0X13YFKXJAxC1WRGF8poV5OkNtvysE',
    appId: '1:17515297820:ios:ce718060570de23f39f3d9',
    messagingSenderId: '17515297820',
    projectId: 'tranquilgo-594b2',
    storageBucket: 'tranquilgo-594b2.firebasestorage.app',
    iosBundleId: 'com.example.tranquilgo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-L0X13YFKXJAxC1WRGF8poV5OkNtvysE',
    appId: '1:17515297820:ios:ce718060570de23f39f3d9',
    messagingSenderId: '17515297820',
    projectId: 'tranquilgo-594b2',
    storageBucket: 'tranquilgo-594b2.firebasestorage.app',
    iosBundleId: 'com.example.tranquilgo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqpiJr74Al3s1I4BXZ4X11aiBeRYeKXhg',
    appId: '1:17515297820:web:e14af8b8b0cc2d7339f3d9',
    messagingSenderId: '17515297820',
    projectId: 'tranquilgo-594b2',
    authDomain: 'tranquilgo-594b2.firebaseapp.com',
    storageBucket: 'tranquilgo-594b2.firebasestorage.app',
    measurementId: 'G-J5VD2HY849',
  );
}
