platform :ios, '10.0'

# Flutter-specific setup
flutter_application_path = File.join('..', 'flutter')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Add this line to integrate Flutter dependencies
  pod 'Flutter', :path => flutter_application_path

  # This line makes sure the Flutter dependencies are included
  pod 'FlutterPluginRegistrant', :path => File.join(flutter_application_path, 'packages', 'flutter_plugin_registrant')
end
