# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# Path to your Flutter project
flutter_application_path = '../'
# load File.join(flutter_application_path, '.dart_tool', 'flutter_ios_podhelper.rb')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  install_all_flutter_pods(flutter_application_path)

  flutter_install_ios_plugin_pods(flutter_application_path)
end

# This post_install hook ensures compatibility with Xcode
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
